spring:
  application:
    name: notification-server
  cloud:
    config:
      enabled: false
  jmx:
    enabled: false
  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8081

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
